import GObject from 'gi://GObject';

export const DEFAULT_PARAMS = {
    frequency: 50, amplitude: 10, octaves: 2,
    vapor_octaves: 4, vapor_speed: 1.5,
    zoom: 1.0, grain: 15, dispersion: 20,
    saturation: 1.0, brightness: 1.0,
    flow_animation_enabled: true, flow_speed_factor: 0.5,
    resize_duration: 1000,
    clip: [0, 0, -1, -1], width: 0, height: 0,
};

export const WAVE_EFFECT_META = {
        GTypeName: "BMSWaveEffect",
        Properties: {
            'frequency': GObject.ParamSpec.double(
                `frequency`,
                `Frequency`,
                `Wave fbm frequency`,
                GObject.ParamFlags.READWRITE,
                0.0, 100.0,
                50.0,
            ),
            'amplitude': GObject.ParamSpec.double(
                `amplitude`,
                `Amplitude`,
                `Wave fbm amplitude`,
                GObject.ParamFlags.READWRITE,
                0.0, 100.0,
                10.0,
            ),
            'octaves': GObject.ParamSpec.int(
                `octaves`,
                `Octaves`,
                `Wave fbm octave count`,
                GObject.ParamFlags.READWRITE,
                0, 6,
                2,
            ),
            'vapor_octaves': GObject.ParamSpec.int(
                `vapor_octaves`,
                `Vapor octaves`,
                `Vapor fbm octave count`,
                GObject.ParamFlags.READWRITE,
                0, 6,
                4,
            ),
            'vapor_speed': GObject.ParamSpec.double(
                `vapor_speed`,
                `Vapor speed`,
                `Speed of the vapor texture to drift`,
                GObject.ParamFlags.READWRITE,
                0.0, 5.0,
                1.5,
            ),
            'grain': GObject.ParamSpec.double(
                `grain`,
                `Grain`,
                `Fine grain noise added to the displacement`,
                GObject.ParamFlags.READWRITE,
                0.0, 100.0,
                15.0,
            ),
            'zoom': GObject.ParamSpec.double(
                `zoom`,
                `Zoom`,
                `Zooms the backdrop toward the surface center`,
                GObject.ParamFlags.READWRITE,
                0.5, 2.0,
                1.0,
            ),
            'dispersion': GObject.ParamSpec.double(
                `dispersion`,
                `Dispersion`,
                `Chromatic aberration shift between the red and blue samples`,
                GObject.ParamFlags.READWRITE,
                0.0, 100.0,
                20.0,
            ),
            'saturation': GObject.ParamSpec.double(
                `saturation`,
                `Saturation`,
                `Final color saturation amount`,
                GObject.ParamFlags.READWRITE,
                0.0, 2.0,
                1.0,
            ),
            'brightness': GObject.ParamSpec.double(
                `brightness`,
                `Brightness`,
                `Final color brightness multiplier`,
                GObject.ParamFlags.READWRITE,
                0.0, 2.0,
                1.0,
            ),
            'flow_animation_enabled': GObject.ParamSpec.boolean(
                `flow_animation_enabled`,
                `Flow animation enabled`,
                `Enable the flow animation`,
                GObject.ParamFlags.READWRITE,
                true,
            ),
            'flow_speed_factor': GObject.ParamSpec.double(
                `flow_speed_factor`,
                `Flow speed factor`,
                `Overall flow speed of the wave and vapor animation`,
                GObject.ParamFlags.READWRITE,
                0.0, 5.0,
                0.5,
            ),
            'resize_duration': GObject.ParamSpec.int(
                `resize_duration`,
                `Resize duration`,
                `Width and height ease duration on resize, in milliseconds`,
                GObject.ParamFlags.READWRITE,
                0, 10000,
                1000,
            ),
            'width': GObject.ParamSpec.double(
                `width`,
                `Width`,
                `Width`,
                GObject.ParamFlags.READWRITE,
                0.0, Number.MAX_SAFE_INTEGER,
                0.0,
            ),
            'height': GObject.ParamSpec.double(
                `height`,
                `Height`,
                `Height`,
                GObject.ParamFlags.READWRITE,
                0.0, Number.MAX_SAFE_INTEGER,
                0.0,
            ),
        }
};
